apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 1Gi  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/primeiro-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube