apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage-classes
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-storage-classes